### ISSUE TITLE
NEED HELP PLEASE

### ISSUE THREAD

**Issue by kenshien564** [basil00/WinDivertTool#2]
sorry i am a complete need when it comes to programing or coding but can anyone please give me a little hand here. how do i go about compiling this windert tool and make it work as a .exe application software? been searching on google for help for 4 days non stop now no answer. also its so hard or no way to contact developer on github as well so its almost like im comletely in the void of outer space all by myself hopelessly lol. anyway can give a noob a hand or video walk through please. i got visual studio, got the files, but dont know how to compile it all together any help please.

https://github.com/basil00/Divert

**Comment by basil00** [comment]
There is currently no support for Visual Studio.  It might be possible to compile the project with VS, but you would have to figure it out by yourself.

Instead, this project must be cross-compiled using MinGW under Linux.  Something like:

    x86_64-w64-mingw32-gcc -O2 -o WinDivertTool.exe WinDivertTool.c -I include/
    x86_64-w64-mingw32-strip WinDivertTool.exe
