### ISSUE TITLE
no application found while certainly there is WinDivert64.sys and it cannot removed because it is used by some application

### ISSUE THREAD

**Issue by taxen** [basil00/WinDivertTool#3]
I downloaded the .exe file and executed the file. There is WinDivert64.sys under "C:\Users\user\AppData\Local\Temp\_MEI44962" in my system. When I try to remove it, an error message pops up and says it won't be removed because another application is using the file.
That is why this tool comes in. When I tried the tool, the result is this in the image below.
![result](https://user-images.githubusercontent.com/3875423/202805892-64138262-e2a1-4bc3-bf56-d36bb1d49164.png)
The description of WinDivert64.sys says the company is Basil's Projects and the file version is 1.0.0.
Here is the result by VirusTotal. https://www.virustotal.com/gui/file/53ab28ec00be6e6f8aefa9ee76fc2735e94d7f3f9dbc06eb2b7ac8cd3084a6af
It seems the file is not malicious.
I just want to know what program the file is used for.
Thank you.

**Comment by basil00** [comment]
Try:

1. Run `WinDivertTool uninstall` first, then try deleting the file.
2. If that does not work, reboot into safe mode and delete the file.

**Comment by taxen** [comment]
Executing the procedure 1 successfully removed the file.
I still do not know what program it was used for.
Maybe next time I come across the file, I will try again.

Thank you.

**Comment by basil00** [comment]
> I still do not know what program it was used for.

I think no program was using it, but the WinDivert service was still installed.  So this probably prevented the deletion of the file.
